# Generated by Django 3.0.9 on 2020-08-31 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='التصنيف', help_text='قم بادخال اسم التصنيف ', max_length=255, verbose_name='التصنيف')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='يفضل تركه فارغا', null=True, unique=True)),
            ],
            options={
                'verbose_name': ' التصنيف',
                'verbose_name_plural': 'التصنيفات ',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='قم بادخال عنوان المنشور', max_length=100, verbose_name='العنوان')),
                ('content', models.TextField(help_text='قم بادخال الوصف', verbose_name='الوصف')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='يفضل تركه فارغا', null=True, unique=True)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now, help_text='يفضل تركه كما هو', verbose_name='تاريخ المنشور')),
                ('post_update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False, verbose_name='تفعيل')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('category', models.ForeignKey(blank=True, help_text='قم باختيار التصنيف', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.Category', verbose_name='التصنيف ')),
            ],
        ),
    ]
