# Generated by Django 3.0.9 on 2020-08-31 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-post_date',), 'verbose_name': 'المنشور', 'verbose_name_plural': 'المنشورات'},
        ),
    ]
