# Generated by Django 3.0.9 on 2020-09-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200901_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostS',
        ),
    ]
