# Generated by Django 3.0.9 on 2020-09-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='التصنيف', help_text='قم بادخال اسم التصنيف ', max_length=255, verbose_name='التصنيف')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='يفضل تركه فارغا', null=True, unique=True)),
            ],
            options={
                'verbose_name': 'تصنيف مخططات رفحاء',
                'verbose_name_plural': 'تصنيف مخططات رفحاء ',
            },
        ),
    ]
