# Generated by Django 3.0.9 on 2020-09-01 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_categorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categorys',
            field=models.ForeignKey(blank=True, help_text='قم باختيار مخططات رفحاء', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pts', to='blog.Category', verbose_name='مخططات رفحاء '),
        ),
    ]
