# Generated by Django 3.0.9 on 2020-09-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_categorys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryS',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categorys',
        ),
    ]
