# Generated by Django 3.0.9 on 2020-09-01 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20200901_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, default=False, null=True, upload_to='media', verbose_name='المخطط'),
        ),
        migrations.CreateModel(
            name='PostS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='قم بادخال عنوان المنشور', max_length=100, verbose_name='العنوان')),
                ('content', models.TextField(help_text='قم بادخال الوصف', verbose_name='الوصف')),
                ('files', models.FileField(blank=True, default=False, null=True, upload_to='media', verbose_name='المخطط')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='يفضل تركه فارغا', null=True, unique=True)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now, help_text='يفضل تركه كما هو', verbose_name='تاريخ المنشور')),
                ('post_update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='تفعيل')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مخططات رفحاء المطوره',
                'verbose_name_plural': 'مخططات رفحاء المطوره',
                'ordering': ('-post_date',),
            },
        ),
    ]
