# Generated by Django 3.0.9 on 2020-09-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_posts_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='title2',
        ),
        migrations.AddField(
            model_name='post',
            name='title2',
            field=models.CharField(blank=True, help_text='قم بادخال عنوان للرابط الذي تريد وضعه او للصوره التي تريد وضعها', max_length=100, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, help_text='قم بادخال الرابط ', null=True, verbose_name='الرابط'),
        ),
    ]
