# Generated by Django 3.0.9 on 2020-09-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200903_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='files',
        ),
        migrations.AddField(
            model_name='post',
            name='files2',
            field=models.FileField(blank=True, help_text='قم باضافتها اذا كنت تريد وضع صوره بدل العنوان', null=True, upload_to='media', verbose_name='صورة العنوان'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='التصنيف', help_text='قم بادخال اسم التصنيف ', max_length=255, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, help_text='قم بادخال العنوان ', max_length=100, null=True, verbose_name='العنوان'),
        ),
    ]
