# Generated by Django 3.0.9 on 2020-08-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics\\defaultpic.png', upload_to='profile_pics'),
        ),
    ]
